export const darkTheme = {
  mode: "dark",
  PRIMARY_BACKGROUND_COLOR: "#06090F",
  SURFACE_COLOR: "#161B22",
  ERROR_COLOR: "#CF6679",
  PRIMARY_COLOR: "#161B22",
  TEXT_COLOR: "#FFFFFF",
  BUTTON_TEXT_COLOR: "#000000",
  COLOR_ACCENT: "#c885ff",
  DIVIDER_COLOR: "rgba(255, 255, 255, 0.12)",
};

export const lightTheme = {
  mode: "light",
  PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
  SURFACE_COLOR: "#FFFFFF",
  ERROR_COLOR: "#B00020",
  PRIMARY_COLOR: "#FFFFFF",
  TEXT_COLOR: "#000000",
  BUTTON_TEXT_COLOR: "#FFFFFF",
  COLOR_ACCENT: "#364DEF",
  DIVIDER_COLOR: "#E5E5E5"
};
